spring:
  main:
    web-application-type: NONE
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "file-parser"

file-parser:
  type:
    simple-local-file:
      supported-types: text/plain
      source-path: watch
      destination-path: processed